apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: kustomize-

resources:
  - guestbook-ui-deployment.yaml
  - guestbook-ui-svc.yaml

images:
  - name: gcr.io/google-samples/gb-frontend
    newTag: v6
    #newTag: v5.2.0  # <-- replace with your desired SemVer
