apiVersion: apps/v1
kind: Deployment

metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=confirm
  name: guestbook-ui-a
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
